name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tmbot:latest

  Cleanup-Workflow-Logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: Cleanup Workflow Logs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GH_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
